version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Update as necessary
    commands:
      - echo "Installing Docker"
      - apt-get update
      - apt-get install -y docker.io
      - echo "Starting Docker using systemctl"
      - systemctl enable docker
      - systemctl start docker
      - usermod -a -G docker $USER
      - echo "Installing Docker Compose"
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      - docker-compose version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo "Pulling MySQL image..."
      - docker-compose pull

  build:
    commands:
      - echo "Building Docker images..."
      - docker-compose build
      - echo "Starting Docker containers..."
      - docker-compose up -d
      - echo "Waiting for MySQL to initialize..."
      - sleep 30 # Adjust as needed
      - echo "Running any tests..."

  post_build:
    commands:
      - echo "Stopping Docker containers..."
      - docker-compose down
      - echo "Build completed."

artifacts:
  files:
    - '**/*'

